name: Auto Data Collection (DISABLED)

# 비활성화: 서버의 cron job이 자동 수집을 처리합니다
# 서버: server.js에서 매일 00:00 KST에 자동 실행
on:
  workflow_dispatch: # 수동 실행만 가능

jobs:
  auto-collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Trigger Auto Collection
      run: |
        curl -X POST https://api.youthbepulse.com/api/auto-collect \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.ADMIN_SHARED_SECRET }}"
      env:
        ADMIN_SHARED_SECRET: ${{ secrets.ADMIN_SHARED_SECRET }}
